sonar.projectKey=J-shw_Menstrudel
sonar.organization=j-shw


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Menstrudel
sonar.projectVersion=4.2.3


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=app/lib
# sonar.dart.lcov.reportPaths=app/coverage/lcov.info # Should not be needed due to new workflow

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-