ALTER TABLE users ADD COLUMN track_bbt BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN track_cervical_mucus BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN hide_sex_chip BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE daily_logs ADD COLUMN sex_activity TEXT NOT NULL DEFAULT 'none';
ALTER TABLE daily_logs ADD COLUMN bbt REAL NOT NULL DEFAULT 0;
ALTER TABLE daily_logs ADD COLUMN cervical_mucus TEXT NOT NULL DEFAULT 'none';
