ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS cycle_length INTEGER NOT NULL DEFAULT 28;
ALTER TABLE users ADD COLUMN IF NOT EXISTS period_length INTEGER NOT NULL DEFAULT 5;
ALTER TABLE users ADD COLUMN IF NOT EXISTS auto_period_fill BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_period_start DATE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_normalized ON users ((lower(trim(email))));
