ALTER TABLE users ADD COLUMN IF NOT EXISTS track_bbt BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS track_cervical_mucus BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS hide_sex_chip BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS sex_activity TEXT NOT NULL DEFAULT 'none';
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS bbt DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS cervical_mucus TEXT NOT NULL DEFAULT 'none';
