ALTER TABLE users ADD COLUMN IF NOT EXISTS shown_period_tip BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS age_group TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS usage_goal TEXT NOT NULL DEFAULT 'health';
ALTER TABLE users ADD COLUMN IF NOT EXISTS unpredictable_cycle BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS long_period_warning_cycle_start DATE;
