name: iOS Release Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest 
    permissions:
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Flutter dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Install Apple certificates and provisioning profile
        uses: apple-actions/import-codesign-certs@v5
        with:
          p12-file-base64: ${{ secrets.APPSTORE_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.APPSTORE_CERTIFICATES_PASSWORD }}

      - name: Build iOS IPA
        working-directory: ./app
        run: flutter build ipa

      - name: Get version from Git tag
        id: get_version
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Upload IPA as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: menstrudel-release-ipa
          path: ./app/build/ios/ipa/*.ipa

      - name: Upload IPA to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./app/build/ios/ipa/menstrudel.ipa 
          asset_name: menstrudel-${{ env.VERSION }}.ipa
          asset_content_type: application/octet-stream